import Head from "next/head";
import styles from "../styles/Home.module.css";
import MasterPage from "../components/masterPage";
import Image from "next/image";

export default function Home({ characters }) {
  return (
    <MasterPage>
      <div className={styles.container}>
        <Head>
          <title>Rick and Morty</title>
          <meta name="description" content="Generated by create next app" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>Welcome to Rick and Marty World!</h1>

          <div>
            <ul className={styles.grid}>
              {characters.map((c) => (
                <li key={c.id} className={styles.card}>
                  <h2>{c.name}</h2>
                </li>
              ))}
            </ul>
          </div>
        </main>
      </div>
    </MasterPage>
  );
}

export async function getStaticProps() {
  const res = await fetch("https://rickandmortyapi.com/api/character");
  const resObj = await res.json();
  const characters = resObj.results;
  console.log("characters", characters);
  return {
    props: {
      characters,
    },
  };
}
